### PR TITLE
Update tests.yml

### PR DESCRIPTION
**Pull request by Cictrone**
needed

### CODE REVIEW

**Comment by Cictrone** [comment]
@KCarretto pls force merge this

**Review by hulto — APPROVED** [review]
LGTM fix those failing test tho ;)

**Comment by Cictrone** [comment]
TODO @KCarretto

**Comment by hulto** [comment]
Also Kyle you'll have to change the required workflows / stages in the GitHub actions UI.
Currently imix and eldritch exist their but not in code so things are hanging.

**Pull request merged**
